### Create a new trip
POST http://localhost:8080/trips
Content-Type: application/json

{
  "destination": "Florida",
  "starts_at": "2024-06-25T21:51:54.7342Z",
  "ends_at": "2024-07-25T21:51:54.7342Z",
  "emails_to_invite": [
    "aaaaa@gmail.com",
    "bbbbb@gmail.com",
    "ccccc@gmail.com"
  ],
  "owner_name": "John Doe",
  "owner_email": "john@gmail.com"
}

### Get trip details
GET http://localhost:8080/trips/683f3bf2-3b18-4d00-be8f-36a590a71995
Content-Type: application/json

### Get trip participants
GET http://localhost:8080/trips/348da708-6e07-447e-a6fd-fc1bc732feb5/participants
Content-Type: application/json

### Update trip
PUT http://localhost:8080/trips/683f3bf2-3b18-4d00-be8f-36a590a71995
Content-Type: application/json

{
  "destination": "Florida, US",
  "starts_at": "2025-06-25T21:51:54.7342Z",
  "ends_at": "2025-07-25T21:51:54.7342Z"
}


### Confirm trip
GET http://localhost:8080/trips/683f3bf2-3b18-4d00-be8f-36a590a71995/confirm
Content-Type: application/json

### Confirm Participant
POST http://localhost:8080/participants/3435c008-1232-4f9a-a3cb-fc88eae0dbb6/confirm
Content-Type: application/json

{
  "name": "AAAAAAA"
}

### Invite Participant
POST http://localhost:8080/trips/683f3bf2-3b18-4d00-be8f-36a590a71995/invite
Content-Type: application/json

{
  "email": "ddddd@gmail.com"
}

### Register activity
POST http://localhost:8080/trips/96b9bd8d-122e-40a4-b394-a9201e98d65a/activities
Content-Type: application/json

{
  "title": "Swimming",
  "occurs_at": "2024-06-25T21:51:54.7342Z"
}

### Get trip activities
GET http://localhost:8080/trips/96b9bd8d-122e-40a4-b394-a9201e98d65a/activities
Content-Type: application/json


### Register link
POST http://localhost:8080/trips/9b29bcb1-a509-41a8-a864-fab800757d72/links
Content-Type: application/json

{
  "title": "Swimming",
  "url": "https://www.google.com"
}

### Get trip links
GET http://localhost:8080/trips/9b29bcb1-a509-41a8-a864-fab800757d72/links
Content-Type: application/json